{ config, lib, pkgs, niriTheming, niriScripts, niriClipboard, niriEmoji, ... }:

# niri's own config. There is no home-manager module for niri, so this is
# written out as a KDL file.
#
# Syntax was checked against niri 26.04's parser (niri-config/src/lib.rs) and
# its shipped default-config.kdl rather than from memory — KDL node and
# property names have moved between releases.
let
  inherit (niriTheming) activeDir;

  bin = pkg: lib.getExe pkg;

  # Per-host display layout, from local.niri.outputs. Empty on hosts that
  # don't set it, which leaves niri to auto-detect.
  renderOutput =
    o:
    let
      lines =
        lib.optional o.off "off"
        ++ lib.optional (o.mode != null) ''mode "${o.mode}"''
        ++ lib.optional (o.scale != null) "scale ${toString o.scale}"
        ++ lib.optional (o.transform != null) ''transform "${o.transform}"''
        ++ lib.optional (o.position != null)
          "position x=${toString o.position.x} y=${toString o.position.y}"
        ++ lib.optional o.variableRefreshRate "variable-refresh-rate"
        ++ lib.optional o.focusAtStartup "focus-at-startup";
    in
    ''
      output "${o.name}" {
      ${lib.concatMapStringsSep "\n" (l: "    ${l}") lines}
      }
    '';

  outputBlocks = lib.concatMapStringsSep "\n" renderOutput config.local.niri.outputs;

  workspaceNames = [ "1" "2" "3" "4" "5" ];

  workspaceBlocks = lib.concatMapStringsSep "\n" (
    n:
    if config.local.niri.workspaceOutput == null then
      ''workspace "${n}"''
    else
      ''
        workspace "${n}" {
            open-on-output "${config.local.niri.workspaceOutput}"
        }''
  ) workspaceNames;

  terminal = "${pkgs.kitty}/bin/kitty";
  launcher = "${pkgs.wofi}/bin/wofi --show drun";
  # finalPackage rather than pkgs.firefox: that's the wrapper home-manager
  # actually installs, carrying whatever ../firefox.nix declares beyond plain
  # prefs. Naming the raw package here would launch a second, unwrapped build.
  #browser = "${config.programs.firefox.finalPackage}/bin/firefox";
  browser = "${pkgs.vivaldi}/bin/vivaldi";
  fileManager = "${pkgs.kdePackages.dolphin}/bin/dolphin";
  # Bare `ranger` so it resolves from PATH to home-manager's wrapped build,
  # which carries the preview tools. The raw ${pkgs.ranger} has none of them.
  fileManagerTui = "${terminal} -e ranger";

  # OpenRGB's tray applet, applying the configured profile at login.
  #
  # `--startminimized` is doing two jobs. OpenRGB drops to CLI mode and exits
  # as soon as it is given any option — `--profile` on its own would apply the
  # lighting and quit, leaving no tray icon — and this both forces the GUI back
  # on (it implies `--gui`) and keeps that GUI out of the way. Passing
  # `--profile` alone, or omitting it, are both wrong for "apply the profile
  # and sit in the tray".
  #
  # Switched off at the moment: the whole binding is commented out below
  # rather than deleted, so re-enabling it is uncommenting two lines. The
  # empty string is what keeps `${openrgbStartup}` in the config template a
  # valid reference while that is the case — with the binding commented out
  # and nothing in its place, evaluating this file fails outright with
  # "undefined variable 'openrgbStartup'".
  openrgbStartup = "";
  #openrgbStartup = lib.optionalString config.local.openrgb.autostart ''
    #spawn-at-startup "${pkgs.openrgb}/bin/openrgb" "--startminimized" "--profile" "${config.local.openrgb.profile}"'';
in
{
  xdg.configFile."niri/config.kdl".text = ''
    // Generated by home/joshr/niri/niri.nix — edit that, not this file.
    //
    // Colours live in the active theme, swapped by `theme-apply`. niri
    // reloads its config automatically when this include target changes.
    include "${activeDir}/niri.kdl"

    // Displays. Set per host in home/joshr/<host>-niri.nix via
    // local.niri.outputs; nothing here means niri auto-detects.
    ${outputBlocks}

    input {
        keyboard {
            numlock
            xkb {
                layout "us"
            }
            repeat-delay 400
            repeat-rate 40
        }

        touchpad {
            tap
            natural-scroll
            dwt
            accel-profile "adaptive"
            scroll-method "two-finger"
        }

        mouse {
            // Flat profile: no pointer acceleration. Matches the setting
            // carried over from the Plasma config.
            accel-profile "flat"
        }

        // Focus follows the mouse only when it crosses into another window.
        focus-follows-mouse max-scroll-amount="0%"

        // Don't let a misbehaving client warp the cursor.
        warp-mouse-to-focus
    }

    layout {
        gaps 12

        center-focused-column "never"

        preset-column-widths {
            proportion 0.33333
            proportion 0.5
            proportion 0.66667
        }

        default-column-width { proportion 0.5; }

        // waybar is a layer-shell panel, so niri already reserves space for
        // it; struts are only extra outer gaps on top of that.
        struts {
            top 0
            bottom 0
            left 0
            right 0
        }
        // Sets the fallback background fill color to solid black
        background-color "#303030"
    }

    // Named workspaces. waybar's niri/workspaces module shows these, and the
    // Mod+<n> binds below jump straight to them.
    //
    // Pinned to an output when local.niri.workspaceOutput is set. niri
    // otherwise creates a workspace on whichever output happens to be
    // focused, so without this the numbered workspaces scatter across
    // displays depending on where you were standing when you first used one.
${workspaceBlocks}

    prefer-no-csd

    // Filename stamp is month-day-year on a 12-hour clock, to match every
    // other clock in the session. That does cost chronological sort order in
    // a file manager — %m-%d-%Y sorts January of every year together — so if
    // you ever want that back, "%Y-%m-%d %H-%M-%S" is the string to restore
    // here and in the `screenshot` script in scripts.nix.
    screenshot-path "~/Pictures/Screenshots/Screenshot from %m-%d-%Y %I-%M-%S %p.png"

    hotkey-overlay {
        skip-at-startup
    }

    environment {
        // Hint toolkits toward Wayland backends.
        NIXOS_OZONE_WL "1"
        MOZ_ENABLE_WAYLAND "1"
        QT_QPA_PLATFORM "wayland;xcb"
        QT_WAYLAND_DISABLE_WINDOWDECORATION "1"
        SDL_VIDEODRIVER "wayland"
        _JAVA_AWT_WM_NONREPARENTING "1"
        // Set by niri itself for its own session; declared here so child
        // processes agree on it.
        XDG_CURRENT_DESKTOP "niri"
        XDG_SESSION_TYPE "wayland"
    }

    cursor {
        xcursor-theme "Bibata-Modern-Ice"
        xcursor-size 24
        hide-when-typing
    }

    // X11 apps (Steam, some games, older Electron) go through
    // xwayland-satellite. The NixOS module installs it; this starts it.
    xwayland-satellite {
        path "${bin pkgs.xwayland-satellite}"
    }

    animations {
        slowdown 0.7
    }

    overview {
        zoom 0.5
    }

    // waybar runs as a systemd user service (see waybar.nix) so the theme
    // switcher can restart it; starting it here as well would give two bars.
    spawn-at-startup "${bin niriScripts.wallpaperRestore}"
    spawn-at-startup "${bin pkgs.openrgb-with-all-plugins} --startminimized --profile Main"

    // nm-applet is deliberately not started. Its tray icon duplicates the
    // waybar `network` module, and that module's click already opens
    // nm-connection-editor, so the applet added an icon and nothing else.

    // Floating dialogs, pickers and popups.
    window-rule {
        match app-id=r#"^org\.keepassxc\.KeePassXC$"#
        match app-id=r#"^org\.gnome\.Calculator$"#
        match app-id=r#"^Bitwarden$"#
        match title="^Picture-in-Picture$"
        match title="^Open File$"
        match title="^Save File$"
        open-floating true
    }

    //kcalc float
    window-rule {
        match app-id="kcalc"
        open-floating true
    	default-column-width { fixed 400; }
    	default-window-height { fixed 550; }	
    }

    // Steam notification
    window-rule {
         match app-id="steam" title=r#"^notificationtoasts_\d+_desktop$"#
         default-floating-position x=10 y=10 relative-to="bottom-right"
         open-focused false
    }

    // File transfer window
    window-rule {
         match app-id="org.kde.dolphin" title="File Transfer"
         open-floating true
         default-floating-position x=16 y=16 relative-to="bottom-right"
         open-focused false
    }	

    // Rounded corners everywhere, matching waybar and wofi.
    window-rule {
        geometry-corner-radius 8
        clip-to-geometry true
    }

    // Games and video players: no rounding, no shadow, and don't let the
    // screen blank on them.
    window-rule {
        match app-id=r#"^steam_app_"#
        match app-id=r#"^gamescope$"#
        match app-id=r#"^mpv$"#
        geometry-corner-radius 0
        clip-to-geometry false
        shadow { off; }
    }

    // Blank the lock screen's own surface out of screencasts.
    layer-rule {
        match namespace="^wofi$"
        shadow { on; }
    }

    binds {
        Mod+Shift+Slash { show-hotkey-overlay; }

        // --- launching -------------------------------------------------
        Mod+Return hotkey-overlay-title="Terminal" { spawn-sh "${terminal}"; }
        Mod+D      hotkey-overlay-title="Applications" { spawn-sh "${launcher}"; }
        Alt+Space  hotkey-overlay-title="Applications" { spawn-sh "${launcher}"; } 
        Mod+E      hotkey-overlay-title="Files" { spawn-sh "${fileManager}"; }
        Mod+Ctrl+E hotkey-overlay-title="Files (ranger)" { spawn-sh "${fileManagerTui}"; }
        Mod+B      hotkey-overlay-title="Browser" { spawn-sh "${browser}"; }

        // --- clipboard -------------------------------------------------
        // Mod+V and Mod+Shift+V are both window management already, so the
        // history lands on the third one in the V family rather than
        // somewhere unrelated. See clipboard.nix.
        Mod+Ctrl+V hotkey-overlay-title="Clipboard history" { spawn "${bin niriClipboard.clipboardHistory}"; }

        // --- emoji ------------------------------------------------------
        // Mod+. because that is what opens the emoji picker on Windows, and
        // that reflex is the whole reason it's here. It cost this key's old
        // binding, `expel-window-from-column`, which moved down to
        // Mod+Shift+Period among the sizing binds. See emoji.nix.
        Mod+Period hotkey-overlay-title="Emoji" { spawn "${bin niriEmoji.emojiPicker}"; }

        // --- session ---------------------------------------------------
        // Lock is Mod+L, matching the Windows/KDE reflex. That costs the
        // vim-key `Mod+L` for focus-column-right — Mod+Right, Mod+scroll and
        // Mod+End all still walk right, so only the h/j/k/l set loses its "l".
        Mod+L hotkey-overlay-title="Lock" { spawn "${bin niriScripts.lockSession}"; }

        // Blank the monitors now, from the lock screen or from the desktop.
        // Any input wakes them; on the lock screen that leaves swaylock
        // exactly where it was, so this is a screen-off, not an unlock.
        //
        // Works while locked with no `allow-when-locked` on it, and that is
        // deliberate rather than an oversight. niri keeps a whitelist of
        // actions that survive the lock — quit, change-vt, suspend,
        // power-off-monitors, power-on-monitors, switch-layout — and lets
        // those through regardless (`allowed_when_locked` in src/input/mod.rs).
        // Setting the property here would in fact be a config *error*: niri
        // only accepts `allow-when-locked` on spawn binds. It's the same
        // whitelist that lets swayidle's 360s blank fire through the lock in
        // lock.nix.
        //
        // Mod+Escape rather than bare Escape because niri intercepts a bound
        // key unconditionally — `should_intercept_key` matches binds before
        // it ever looks at the lock state, and only *then* is the action
        // dropped if the session is locked and the action isn't whitelisted.
        // So a bare `Escape` bind would swallow Escape in every application,
        // all the time: no dismissing a dialog, no leaving vim's insert mode,
        // no closing a wofi prompt. There is no "only while locked" bind
        // flag to scope it with — the full set is repeat, cooldown-ms,
        // allow-when-locked, allow-inhibiting and hotkey-overlay-title.
        Mod+Escape hotkey-overlay-title="Blank monitors" { power-off-monitors; }

        Mod+Shift+Escape hotkey-overlay-title="Session menu" { spawn "${bin niriScripts.sessionMenu}"; }
        Mod+Shift+E { quit; }
        Ctrl+Alt+Delete { quit; }
        Mod+Shift+I hotkey-overlay-title="Stay awake (toggle)" { spawn "${bin niriScripts.idleInhibit}" "toggle"; }

        // --- theming ---------------------------------------------------
        // Random theme, or pick one / a wallpaper from a menu. Mod+Shift is
        // the random half of both pairs, Mod+Ctrl the deliberate half.
        // `theme-cycle` still exists on PATH if you want the ordered walk.
        Mod+Shift+T hotkey-overlay-title="Random theme" { spawn "${bin niriScripts.themeRandom}"; }
        Mod+Ctrl+T  hotkey-overlay-title="Choose theme" { spawn "${bin niriScripts.themeMenu}"; }
        Mod+Shift+W hotkey-overlay-title="Random wallpaper" { spawn "${bin niriScripts.wallpaperRandom}"; }
        Mod+Ctrl+W  hotkey-overlay-title="Choose wallpaper" { spawn "${bin niriScripts.wallpaperMenu}"; }

        // --- screenshots -----------------------------------------------
        // Region capture goes through satty for annotation; the plain
        // screen/window captures use niri's own actions, which already know
        // the exact geometry.
        //
        // `last` re-shoots the region selected the time before, with no
        // slurp step — for taking the same frame repeatedly, where redrawing
        // the box by hand is both the tedious part and the reason successive
        // shots don't line up. It falls back to a selection if there's no
        // remembered region yet, or if that region has gone off-screen.
        Print              hotkey-overlay-title="Screenshot region" { spawn "${bin niriScripts.screenshot}"; }
        Shift+Print        hotkey-overlay-title="Screenshot last region" { spawn "${bin niriScripts.screenshot}" "last"; }
        Ctrl+Print         { screenshot-screen; }
        Alt+Print          { screenshot-window; }
        Mod+Shift+S        hotkey-overlay-title="Screenshot region" { spawn "${bin niriScripts.screenshot}"; }
        Mod+Ctrl+S         hotkey-overlay-title="Screenshot last region" { spawn "${bin niriScripts.screenshot}" "last"; }

        // --- media / hardware keys -------------------------------------
        XF86AudioRaiseVolume allow-when-locked=true { spawn-sh "${pkgs.wireplumber}/bin/wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05+ -l 1.0"; }
        XF86AudioLowerVolume allow-when-locked=true { spawn-sh "${pkgs.wireplumber}/bin/wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05-"; }
        XF86AudioMute        allow-when-locked=true { spawn-sh "${pkgs.wireplumber}/bin/wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"; }
        XF86AudioMicMute     allow-when-locked=true { spawn-sh "${pkgs.wireplumber}/bin/wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"; }

        XF86AudioPlay allow-when-locked=true { spawn "${bin pkgs.playerctl}" "play-pause"; }
        XF86AudioStop allow-when-locked=true { spawn "${bin pkgs.playerctl}" "stop"; }
        XF86AudioPrev allow-when-locked=true { spawn "${bin pkgs.playerctl}" "previous"; }
        XF86AudioNext allow-when-locked=true { spawn "${bin pkgs.playerctl}" "next"; }

	// Launch calcultor
	XF86Calculator { spawn-sh "${pkgs.kdePackages.kcalc}/bin/kcalc"; }

        // `brightness` rather than brightnessctl directly: it steps *every*
        // backlight device, where brightnessctl on its own takes the first
        // one it finds. That's the same thing on the laptop's single internal
        // panel, but the desk has one device per monitor (see
        // modules/nixos/ddcci.nix) and only one of them would move.
        XF86MonBrightnessUp   allow-when-locked=true { spawn "${bin niriScripts.brightness}" "up"; }
        XF86MonBrightnessDown allow-when-locked=true { spawn "${bin niriScripts.brightness}" "down"; }

        // --- window management -----------------------------------------
        Mod+Q repeat=false { close-window; }
        Alt+F4 repeat=false { close-window; }
        Mod+O repeat=false { toggle-overview; }
        Mod+Tab repeat=false { toggle-overview; }

        Mod+Left  { focus-column-left; }
        Mod+Down  { focus-window-down; }
        Mod+Up    { focus-window-up; }
        Mod+Right { focus-column-right; }
        Mod+H     { focus-column-left; }
        Mod+J     { focus-window-down; }
        Mod+K     { focus-window-up; }
        // No Mod+L here — it locks the session (see the session binds above).

        Mod+Ctrl+Left  { move-column-left; }
        Mod+Ctrl+Down  { move-window-down; }
        Mod+Ctrl+Up    { move-window-up; }
        Mod+Ctrl+Right { move-column-right; }
        Mod+Ctrl+H     { move-column-left; }
        Mod+Ctrl+J     { move-window-down; }
        Mod+Ctrl+K     { move-window-up; }
        Mod+Ctrl+L     { move-column-right; }

        Mod+Home { focus-column-first; }
        Mod+End  { focus-column-last; }

        // --- workspaces -------------------------------------------------
        Mod+Page_Down      { focus-workspace-down; }
        Mod+Page_Up        { focus-workspace-up; }
        Mod+U              { focus-workspace-down; }
        Mod+I              { focus-workspace-up; }
        Mod+Ctrl+Page_Down { move-column-to-workspace-down; }
        Mod+Ctrl+Page_Up   { move-column-to-workspace-up; }

        Mod+1 { focus-workspace "1"; }
        Mod+2 { focus-workspace "2"; }
        Mod+3 { focus-workspace "3"; }
        Mod+4 { focus-workspace "4"; }
        Mod+5 { focus-workspace "5"; }

        Mod+Shift+1 { move-column-to-workspace "1"; }
        Mod+Shift+2 { move-column-to-workspace "2"; }
        Mod+Shift+3 { move-column-to-workspace "3"; }
        Mod+Shift+4 { move-column-to-workspace "4"; }
        Mod+Shift+5 { move-column-to-workspace "5"; }

        // --- scrolling --------------------------------------------------
        // Mod + scroll moves along the row of windows. niri lays windows out
        // on one horizontal strip, so a vertical scroll mapping to
        // left/right is the natural gesture: spin the wheel and you travel
        // the strip.
        //
        // Wheel and touchpad are bound separately — they're distinct
        // triggers, so binding only WheelScroll* leaves the touchpad dead.
        // No cooldown here: unlike workspace switching, stepping several
        // windows in one flick is the point.
        Mod+WheelScrollDown    { focus-column-right; }
        Mod+WheelScrollUp      { focus-column-left; }
        Mod+WheelScrollRight   { focus-column-right; }
        Mod+WheelScrollLeft    { focus-column-left; }

        Mod+TouchpadScrollDown  { focus-column-right; }
        Mod+TouchpadScrollUp    { focus-column-left; }
        Mod+TouchpadScrollRight { focus-column-right; }
        Mod+TouchpadScrollLeft  { focus-column-left; }

        // Workspaces move to Mod+Shift+scroll, since Mod+scroll now walks
        // windows. Kept on a cooldown so one flick is one workspace.
        Mod+Shift+WheelScrollDown     cooldown-ms=150 { focus-workspace-down; }
        Mod+Shift+WheelScrollUp       cooldown-ms=150 { focus-workspace-up; }
        Mod+Shift+TouchpadScrollDown  cooldown-ms=150 { focus-workspace-down; }
        Mod+Shift+TouchpadScrollUp    cooldown-ms=150 { focus-workspace-up; }

        // Carry the focused column with you.
        Mod+Ctrl+WheelScrollDown    cooldown-ms=150 { move-column-to-workspace-down; }
        Mod+Ctrl+WheelScrollUp      cooldown-ms=150 { move-column-to-workspace-up; }
        Mod+Ctrl+TouchpadScrollDown cooldown-ms=150 { move-column-to-workspace-down; }
        Mod+Ctrl+TouchpadScrollUp   cooldown-ms=150 { move-column-to-workspace-up; }

        // --- monitors ---------------------------------------------------
        Mod+Shift+Left  { focus-monitor-left; }
        Mod+Shift+Right { focus-monitor-right; }
        Mod+Shift+Ctrl+Left  { move-column-to-monitor-left; }
        Mod+Shift+Ctrl+Right { move-column-to-monitor-right; }

        // --- sizing -----------------------------------------------------
        Mod+R       { switch-preset-column-width; }
        Mod+Shift+R { switch-preset-window-height; }
        Mod+F       { maximize-column; }
        Mod+Shift+F { fullscreen-window; }
        Mod+M       { maximize-window-to-edges; }
        Mod+C       { center-column; }
        Mod+Minus   { set-column-width "-10%"; }
        Mod+Equal   { set-column-width "+10%"; }
        Mod+Shift+Minus { set-window-height "-10%"; }
        Mod+Shift+Equal { set-window-height "+10%"; }

        Mod+BracketLeft  { consume-or-expel-window-left; }
        Mod+BracketRight { consume-or-expel-window-right; }
        Mod+Comma  { consume-window-into-column; }
        // Expel is on Mod+Shift+Period rather than beside its Mod+Comma
        // partner, because Mod+Period is the emoji picker now. Nothing is
        // lost either way — Mod+BracketLeft/Right already consume and expel,
        // and they're the pair that reads as a direction.
        Mod+Shift+Period { expel-window-from-column; }

        Mod+V       { toggle-window-floating; }
        Mod+Shift+V { switch-focus-between-floating-and-tiling; }
        // Titled so it shows up in the Important Hotkeys overlay at all.
        // That page is niri's own hardcoded list of actions plus whatever
        // carries a hotkey-overlay-title, and tabbed display isn't on the
        // hardcoded list — float and float/tile focus just above it are,
        // which is why they need no title and this does.
        Mod+W hotkey-overlay-title="Tabbed column (toggle)" { toggle-column-tabbed-display; }

        Mod+Shift+P { power-off-monitors; }
    }
  '';
}
