{ ... }:

# The kernel for the desk machine: which one it boots, and the command line it
# boots with.
#
# Imported by both `gamestation` and `gamestation-niri` — they're the same
# physical box, so both belong to the hardware rather than to either session.
# It lives here rather than in hardware-configuration.nix because that file is
# regenerated by `nixos-generate-config` and says so at the top.
#
# The name is narrower than the file now is, and stays that way on purpose: a
# dozen comments across modules/ and MANUAL.md point at
# `hosts/gamestation/kernel-params.nix` by name, and renaming it to chase the
# second half would churn all of them for nothing.
#
# Check what actually took effect with `cat /proc/cmdline` after a reboot;
# these are appended to whatever the bootloader already passes.
{
  imports = [
    # Which kernel, rather than how it is booted. See modules/nixos/kernel.nix
    # for what the CachyOS build changes, what follows it out of the flake's
    # package set, and the command line the *first* rebuild needs.
    ../../modules/nixos/kernel.nix
  ];

  # The CachyOS kernel, BORE variant.
  #
  # The desk is the only machine here where the scheduler is worth an opinion:
  # it plays games while an ollama, a Docker daemon and a browser are all
  # resident, and BORE is the patch that stops a long-running batch job from
  # being treated as the equal of a render thread waking sixty times a second.
  # The rest of the CachyOS patch set comes with it.
  #
  # `variant` is left at its default, which is the plain GCC build rather than
  # upstream's Clang+ThinLTO one — the conservative half of the pair, and the
  # one every out-of-tree module here has the least to argue with. See
  # `local.kernel.cachyos.variant` in modules/nixos/options.nix for the LTO and
  # CPU-optimised builds, and for why picking one off that list matters more
  # than it looks (an uncached variant is an hour of compiling; a `-v3` or
  # `-zen4` build on a CPU without the instructions is a machine that does not
  # boot).
  #
  # This is a reboot, not a `nixos-rebuild test` — see the module header for
  # the way back.
  local.kernel.cachyos.enable = true;

  boot.kernelParams = [
    # Let i2c drivers touch regions the ACPI tables have claimed.
    #
    # This is what OpenRGB needs to reach SMBus-attached RGB controllers —
    # RAM, and most motherboard headers. Without it the kernel's i2c-piix4 /
    # i2c-nct6775 drivers refuse to bind and OpenRGB shows the GPU and
    # nothing else.
    #
    # The "lax" in the name is real: it's the kernel declining to arbitrate
    # between ACPI and a driver reaching for the same registers. In practice
    # it's what every RGB-control setup runs with, but it is a guard being
    # switched off, not a feature being switched on.
    "acpi_enforce_resources=lax"

    # NOT here: "i2c-dev". It was, and it never did anything — i2c-dev is a
    # *module* name, and the kernel ignores an unrecognised word on its
    # command line. The module is loaded properly by
    # `services.hardware.openrgb.enable` (modules/nixos/gaming.nix) and by
    # `hardware.i2c.enable` (modules/nixos/ddcci.nix), both of which set
    # boot.kernelModules, which is why nothing ever noticed.

    # Give the NVIDIA DRM driver a framebuffer console.
    #
    # nvidia.nix already sets `modesetting.enable`, which is `nvidia_drm
    # .modeset=1`; this is the other half. Without it the console hands off
    # to simpledrm and you get a flicker, a resolution change, or a black VT
    # between the bootloader and the greeter — most visible on this machine
    # because it's the one with a discrete NVIDIA card.
    "nvidia_drm.fbdev=1"

    # AMD IOMMU on, in passthrough mode.
    #
    # `amd_iommu=on` turns the unit on; `iommu=pt` tells it to identity-map
    # the host's own devices instead of translating for them, so the DMA
    # remapping cost is paid only by devices actually handed to a guest.
    #
    # Together these are the prerequisite for VFIO device passthrough to a
    # VM. They do nothing on their own — no device is bound to vfio-pci here
    # — but the IOMMU groups don't exist to look at until the machine has
    # booted with them, so they go on ahead of the rest.
    "amd_iommu=on"
    "iommu=pt"
  ];
}
