{ ... }:

# Kernel command line for the desk machine.
#
# Imported by both `gamestation` and `gamestation-niri` — they're the same
# physical box, so the flags belong to the hardware rather than to either
# session. It lives here rather than in hardware-configuration.nix because
# that file is regenerated by `nixos-generate-config` and says so at the top.
#
# Check what actually took effect with `cat /proc/cmdline` after a reboot;
# these are appended to whatever the bootloader already passes.
{
  boot.kernelParams = [
    # Let i2c drivers touch regions the ACPI tables have claimed.
    #
    # This is what OpenRGB needs to reach SMBus-attached RGB controllers —
    # RAM, and most motherboard headers. Without it the kernel's i2c-piix4 /
    # i2c-nct6775 drivers refuse to bind and OpenRGB shows the GPU and
    # nothing else.
    #
    # The "lax" in the name is real: it's the kernel declining to arbitrate
    # between ACPI and a driver reaching for the same registers. In practice
    # it's what every RGB-control setup runs with, but it is a guard being
    # switched off, not a feature being switched on.
    "acpi_enforce_resources=lax"

    # Give the NVIDIA DRM driver a framebuffer console.
    #
    # nvidia.nix already sets `modesetting.enable`, which is `nvidia_drm
    # .modeset=1`; this is the other half. Without it the console hands off
    # to simpledrm and you get a flicker, a resolution change, or a black VT
    # between the bootloader and the greeter — most visible on this machine
    # because it's the one with a discrete NVIDIA card.
    "nvidia_drm.fbdev=1"

    # AMD IOMMU on, in passthrough mode.
    #
    # `amd_iommu=on` turns the unit on; `iommu=pt` tells it to identity-map
    # the host's own devices instead of translating for them, so the DMA
    # remapping cost is paid only by devices actually handed to a guest.
    #
    # Together these are the prerequisite for VFIO device passthrough to a
    # VM. They do nothing on their own — no device is bound to vfio-pci here
    # — but the IOMMU groups don't exist to look at until the machine has
    # booted with them, so they go on ahead of the rest.
    "amd_iommu=on"
    "iommu=pt"
  ];
}
