{ ... }:

# Which app opens which kind of file — as a *baseline the desktop can
# override*, rather than as something nailed shut.
#
# The problem this solves
# -----------------------
# These defaults used to be home-manager's `xdg.mimeApps`, in
# home/joshr/niri/browser.nix and home/joshr/niri/mime.nix. That option owns
# ~/.config/mimeapps.list and writes it as a read-only symlink into the store.
#
# That same file is the one every interactive "make this the default" writes
# to: Dolphin's "Open With… → Remember application association for this type
# of file", KDE's File Associations panel, Plasma's Default Applications page,
# and "set as default" inside a browser. With home-manager holding it, all of
# them appear to work and none of them persist — which is why System Settings
# looked broken, and why declaring Gwenview in Nix was the only thing that
# stuck.
#
# So the declarations move down a level instead of holding the file hostage.
# XDG's mime-apps spec reads these in order of *decreasing* precedence:
#
#     $XDG_CONFIG_HOME/$desktop-mimeapps.list
#     $XDG_CONFIG_HOME/mimeapps.list           <- the user's; left writable now
#     $XDG_CONFIG_DIRS/$desktop-mimeapps.list
#     $XDG_CONFIG_DIRS/mimeapps.list           <- this file
#
# $XDG_CONFIG_DIRS is /etc/xdg, so what is written here applies on a fresh
# install and on every rebuild, while anything chosen in a GUI lands in the
# user's own file and outranks it. Declarative defaults *and* a settings panel
# that works, instead of one at the cost of the other.
#
# `[Default Applications]` is honoured here specifically because /etc/xdg is a
# config directory. The spec only reads that group from $XDG_CONFIG_HOME and
# $XDG_CONFIG_DIRS — in the deprecated $XDG_DATA_* locations it would be
# ignored and only the association groups would count, which is the other
# reason this is /etc/xdg and not a data dir.
#
# Not the seed-once approach used for ~/.gitconfig in home/common/git.nix: a
# seed is written once and then drifts, whereas this stays live underneath the
# user's file for as long as it exists.
#
# Imported from ./desktop.nix, so it reaches all four desktop hosts and not
# the server. Both sessions benefit — this is the first time the Plasma hosts
# get the browser default declaratively, since the reason they were kept away
# from `xdg.mimeApps` was precisely that it broke their settings page.
let
  # Upstream-fixed desktop entry IDs, both listed with a fallback spelling.
  # mimeapps.list treats a `;`-separated value as a preference list and skips
  # entries it can't resolve, so a wrong name is a silent no-op rather than an
  # error — cheap insurance, and the reason home/joshr/browser.nix has always
  # named two for Vivaldi.

  # nixpkgs keeps the name from Vivaldi's upstream .deb and never renames it
  # to match the binary, so the entry ID is `vivaldi-stable.desktop`. See
  # home/joshr/browser.nix, which installs it and sets $BROWSER.
  browser = "vivaldi-stable.desktop;vivaldi.desktop";

  # Checked against KDE's own app/CMakeLists.txt and the shipped file list
  # rather than from memory — KDE moved its desktop entries to reverse-DNS
  # years ago, so the bare name is the fallback and not the other way round.
  #
  # Gwenview is installed by ./desktop-apps.nix, which only gamestation-niri
  # imports. On the other three hosts this entry simply doesn't resolve and
  # the next handler wins.
  images = "org.kde.gwenview.desktop;gwenview.desktop";

  # Haruna is the default video player
  videos = "org.kde.haruna.desktop;haruna.desktop";

  # Elisa is the default music player
  music = "org.kde.elisa.desktop;elisa.desktop";
in
{
  environment.etc."xdg/mimeapps.list".text = ''
    # Generated by modules/nixos/default-apps.nix — edit that, not this file.
    #
    # This is the system baseline. Anything set in a GUI is written to
    # ~/.config/mimeapps.list, which the spec reads first and which nothing
    # here manages, so a choice made there overrides what follows.
    [Default Applications]
    text/html=${browser}
    application/xhtml+xml=${browser}
    x-scheme-handler/http=${browser}
    x-scheme-handler/https=${browser}
    x-scheme-handler/about=${browser}
    x-scheme-handler/unknown=${browser}

    image/jpeg=${images}
    image/png=${images}
    image/gif=${images}
    image/webp=${images}
    image/tiff=${images}
    image/bmp=${images}
    image/avif=${images}
    image/heif=${images}

    video/mp4=${videos}
    video/mpeg=${videos}
    video/quicktime=${videos}
    video/x-msvideo=${videos}
    video/x-matroska=${videos}
    video/webm=${videos}

    audio/mpeg=${music}
    audio/wav=${music}
    audio/flac=${music}
    audio/ogg=${music}
    audio/x-vorbis+ogg=${music}
    audio/aac=${music}
  '';
}
